version: "3.9"

services:
    mysql:
        image: mysql:8
        container_name: mahjong-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: strongrootpass
            MYSQL_DATABASE: mahjong_stats
            MYSQL_USER: mahjong
            MYSQL_PASSWORD: strongpassword
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    nodeapp:
        build: .
        container_name: mahjong-node
        restart: always
        ports:
            - "3000:3000"
        environment:
            DB_HOST: mysql
            DB_USER: mahjong
            DB_PASS: strongpassword
            DB_NAME: mahjong_stats
        depends_on:
            - mysql

volumes:
    db_data:
